services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
      target: development
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ./envs/.env.test.example:/home/node/app/envs/.env.test:ro
      - ./envs/.env.e2e.example:/home/node/app/envs/.env.e2e:ro
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      NODE_ENV: test
      RABBITMQ_URI: amqp://${RABBITMQ_DEFAULT_USER:-admin}:${RABBITMQ_DEFAULT_PASS:-admin}@rabbitmq:5672
      RABBITMQ_REGISTER_HANDLER: "true"

  rabbitmq:
    build: ./.docker/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-admin}
    tmpfs:
      - /var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
