FROM node:22.17.1-slim AS development

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends python3 make g++ \
    && rm -rf /var/lib/apt/lists/*

USER node

RUN mkdir /home/node/app

WORKDIR /home/node/app

COPY --chown=node:node package*.json ./
RUN npm_config_build_from_source=true npm_config_nodedir=/usr/local npm ci

COPY --chown=node:node . .

CMD [ "tail", "-f", "/dev/null" ]

FROM development AS builder

RUN npm run build

ENV NODE_ENV=production

RUN npm prune --omit=dev

FROM node:22.17.1-slim AS production

USER node

RUN mkdir /home/node/app

WORKDIR /home/node/app

COPY --chown=node:node --from=builder /home/node/app/dist ./dist
COPY --chown=node:node --from=builder /home/node/app/node_modules ./node_modules
COPY --chown=node:node --from=builder /home/node/app/package.json ./

EXPOSE 3000

ENV NODE_ENV=production

CMD [ "npm", "run", "start:prod" ]
