services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: on-failure
    ports:
      - "3000:3000"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ./envs/.env
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      NODE_ENV: production
      DB_VENDOR: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE:-micro_videos}
      DB_USERNAME: root
      DB_PASSWORD: ${DB_PASSWORD:-root}
      DB_LOGGING: "false"
      DB_AUTO_LOAD_MODELS: "true"
      RABBITMQ_URI: amqp://${RABBITMQ_DEFAULT_USER:-admin}:${RABBITMQ_DEFAULT_PASS:-admin}@rabbitmq:5672
      RABBITMQ_REGISTER_HANDLER: "true"

  db:
    image: mysql:8.0.30-debian
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-micro_videos}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
    tmpfs:
      - /var/lib/mysql
    security_opt:
      - seccomp:unconfined
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s

  rabbitmq:
    build: ./.docker/rabbitmq
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-admin}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-admin}
    tmpfs:
      - /var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
